# Install the pre-commit hooks below with
# 'pre-commit install'

# Auto-update the version of the hooks with
# 'pre-commit autoupdate'

# Run the hooks on all files with
# 'pre-commit run --all'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
    # only include python files
    files: \.py$
  - id: debug-statements
    # only include python files
    files: \.py$
  - id: trailing-whitespace
    # only include python files
    files: \.py$

- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.982'
  hooks:
  - id: mypy
    files: (jax/|tests/typing_test\.py)
    exclude: jax/_src/basearray.py  # Use pyi instead
    additional_dependencies: [types-requests==2.29.0, jaxlib==0.4.7, ml_dtypes==0.2.0, numpy==1.24.3, scipy==1.10.1]
    args: [--config=pyproject.toml]

- repo: https://github.com/mwouts/jupytext
  rev: v1.14.4
  hooks:
  - id: jupytext
    args: [--sync]
